services:
  app:
    build: .
    ports:
      - 7999:7999
    expose:
      - "7999"
    env_file: ".env"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt:ro"  # SSL-сертификаты
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"  # Конфиг Nginx
    depends_on:
      - app